# Generated by Django 4.0.2 on 2022-05-18 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0026_anons'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='is_anonsed',
            field=models.BooleanField(default=False),
        ),
    ]
