# Generated by Django 4.0.2 on 2022-05-18 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0028_book_time_create_book_time_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='year_of_creation',
            field=models.IntegerField(default=2000),
            preserve_default=False,
        ),
    ]
