# Generated by Django 4.0.2 on 2022-05-18 18:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0030_alter_author_options_alter_book_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Anons',
        ),
        migrations.AddField(
            model_name='author',
            name='photo',
            field=models.ImageField(default=0, upload_to='photos/%Y/%m/%d/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='photo',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='photos/%Y/%m/%d/'),
            preserve_default=False,
        ),
    ]
