# Generated by Django 4.0.2 on 2022-05-25 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0031_delete_anons_author_photo_book_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='summary_author',
            field=models.TextField(help_text='Enter a brief description of the book', max_length=1000, null=True, verbose_name='Коротко про книгу'),
        ),
    ]
